version: '3.1'

services:
  testDb:
    container_name: todoRestGraphQlSampleTest
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_USER: test
    ports:
      - 5432:5432