site_name: "bootstrapPlay2 Doc"
theme:
  logo: "/doc/innFactoryIcon.svg"
  favicon: "/doc/innFactoryIcon.svg"
  name: material
  features:
    - tabs
  language: en
  palette:
    scheme: default
    primary: red
    accent: red
repo_name: todo-rest-graphql-sample
repo_url: http://localhost:9000/todo-rest-graphql-sample
plugins:
  - search
  - awesome-pages