name: Schema Validation

on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Validate Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'master:schema.graphql'
          approve-label: 'expected-breaking-change'
          # fail-on-breaking: true # default true
          # endpoint: '' # e.g. 'https://example.com/graphql'